/**
 * The upstream provenance record for the vendored spec.
 *
 * Records what was fetched, from where, and what it hashed to. Two jobs:
 *
 *  - Tells a reader where `specs/discord.json` came from, so the vendored file
 *    is never mistaken for something hand-authored.
 *  - Distinguishes "upstream changed" from "our surface changed". Discord's full
 *    document moves most days; the six operations this client binds move rarely.
 *    Recording the raw upstream hash lets the nightly job record that it looked,
 *    and correctly release nothing, instead of re-diffing from scratch.
 */
import { createHash } from 'node:crypto'

export function sha256(text) {
  return createHash('sha256').update(text, 'utf8').digest('hex')
}

export function buildLock({ url, rawBody, spec, surfaceSha, fetchedAt }) {
  return {
    $comment: 'Generated by tools/src/cli.mjs. Do not edit by hand.',
    upstream: {
      url,
      rawSha256: sha256(rawBody),
      specVersion: spec?.info?.version ?? null,
      specTitle: spec?.info?.title ?? null,
    },
    surface: {
      // Hash of the filtered, versioned document — the thing releases track.
      sha256: surfaceSha,
    },
    fetchedAt,
  }
}

export function serialiseLock(lock) {
  return `${JSON.stringify(lock, null, 2)}\n`
}
